config/routes.rb
Rails.application.routes.draw do
  get 'tasks', to: 'tasks#index'
  post 'tasks', to: 'tasks#create'
  get 'tasks/new', to: 'tasks#new', as: :new_task
  get 'tasks/:id', to: 'tasks#show', as: :task
  get 'tasks/:id/edit', to: 'tasks#edit', as: :edit_task
  patch 'tasks/:id', to: 'tasks#update'
  delete 'tasks/:id', to: 'tasks#destroy'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/task.rb
class Task < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_task, only: [ :show, :edit, :update, :destroy ]

  def index
    @tasks = Task.all
  end

  def show
  end

  def new
    @task = Task.new
  end

  def create
    task = Task.new(task_params)
    task.save
    redirect_to tasks_path
  end

  def edit
  end

  def update
    @task.update(task_params)
    redirect_to tasks_path
  end

  def destroy
    @task.destroy
    redirect_to tasks_path
  end

  private

  def set_task
    @task = Task.find(params[:id])
  end

  def task_params
    params.require(:task).permit(:title, :details, :completed)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTaskManager</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tasks/_form.html.erb
<%= form_for(@task) do |f| %>
  <div class="form-group">
    <%= f.label :title %>
    <%= f.text_field :title, class: 'form-control' %>
  </div>

  <div class="form-group mt-3">
    <%= f.label :details %>
    <%= f.text_area :details, class: 'form-control' %>
  </div>

  <% unless f.object.new_record? %>
  <#% still work with if @task.id %>
    <div class="checkbox mt-3">
      <label>
        <%= f.check_box :completed %> Completed
      </label>
    </div>
  <% end %>
  <div class="d-flex align-items-center justify-content-between">
    <%= link_to tasks_path do %>
      <i class="fa fa-backward mt-4" aria-hidden="true"></i>
    <% end %>
    <%= f.submit class: 'btn btn-outline-primary mt-4' %>
  </div>
<% end %>

app/views/tasks/edit.html.erb
<div class="row justify-content-center">
  <div class='col-6'>
    <h1 class='mb-4 mt-5 text-center'>EDIT TASK</h1>
      <%= render 'form', task: @task %>
  </div>
</div>

app/views/tasks/index.html.erb
<div class="row justify-content-center">
  <div class='col-6'>
    <h1 class='mb-4 mt-5 text-center'>TASKS</h1>
    <% @tasks.each do |task| %>
      <p>
        <% if task.completed %>
          <%= link_to task_path(task, task: { completed: false }), data: { 'turbo-method': :patch }, class: 'text-decoration-none text-dark' do %>
            <i class="fa fa-check-square mx-3" aria-hidden="true"></i>
          <% end %>
        <% else %>
          <%= link_to task_path(task, task: { completed: true }), data: { 'turbo-method': :patch }, class: 'text-decoration-none text-dark' do %>
           <i class="fa-solid fa-square mx-3"></i>
          <% end %>
        <% end %>
        <%= link_to task_path(task.id), data: { "turbo-method": :delete, 'turbo-confirm': "Delete #{task.title}?" }, class: 'text-decoration-none text-dark' do %>
          <i class="fa-solid fa-trash-can mx-1"></i>
        <% end %>
        <%= link_to task.title, task_path(task), class: 'text-decoration-none text-dark' %>
      </p> 
    <% end %>

    <hr>

    <%= link_to new_task_path, class: 'btn btn-outline-success' do %>
      <i class="fa fa-plus"></i> Add a new task
    <% end %>
  </div>
</div>

app/views/tasks/new.html.erb
<div class="row justify-content-center">
  <div class='col-6'>
    <h1 class='mb-4 mt-5 text-center'>NEW TASK</h1>
      <%= render 'form', task: @task %>
  </div>
</div>

app/views/tasks/show.html.erb
<div class="row justify-content-center">
  <div class='col-6 mt-5'>
    <h1 class='text-center'><%= @task.title %>
      <% if @task.completed %>
        <i class="fa fa-check" aria-hidden="true"></i>
      <% end %>
    </h1>
    <p class='mt-4 text-center'><%= @task.details %></p>
  </div>
</div>